spring:
  profiles:
    active: local #激活环境，请勿更改，如需改变环境请通过启动参数传入
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          filters:
            #- StripPrefix=1 # 转发之前去掉几层路径
          url-expression: "'lb://'+serviceId"
          lower-case-service-id: true
      globalcors:
        cors‐configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowHeaders: "*"

  main:
    web-application-type: reactive

sa-token:
  # jwt秘钥
  jwt-secret-key: twwgasdask412ksafn13


