spring:
  profiles:
    active: local #激活环境，请勿更改，如需改变环境请通过启动参数传入
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          filters:
            #- StripPrefix=1 # 转发之前去掉几层路径
          url-expression: "'lb://'+serviceId"

