server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_gateway?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 5
      driver-class-name: com.mysql.cj.jdbc.Driver
